Repository wecode-bootcamp-korea/45-backend-westagram-2, pull requests merged in 2023-04, with the labels that each got.

#1 [이지은] Assignment1: Express API - 초기 환경 세팅
  Jieun/.env.sample
  Jieun/.gitignore
  Jieun/app.js
  Jieun/package-lock.json
  Jieun/package.json
Labels: 리뷰 진행 중

#2 [하지현] Assignment1: Express API - 초기 환경 세팅
  jihyeon/.env.sample
  jihyeon/.gitignore
  jihyeon/app.js
  jihyeon/package-lock.json
  jihyeon/package.json
Labels: 리뷰 진행 중

#4 [장인석] Assignment 1: Express API - 초기 환경 세팅
  Inseok_45/.env.sample
  Inseok_45/.gitignore
  Inseok_45/app.js
  Inseok_45/package-lock.json
  Inseok_45/package.json
Labels: 멘토 리뷰 요청

#3 [이지은] Assignment2: 유저 회원가입 하기
  Jieun/.env.sample
  Jieun/.gitignore
  Jieun/app.js
  Jieun/db/migrations/20230418011847_create_users_table.sql
Labels: 멘토 리뷰 요청

#6 [하지현] Assignment 2: Express API - 유저 회원가입 하기
  jihyeon/.gitignore
  jihyeon/app.js
  jihyeon/db/migrations/20230418083046_users.sql
Labels: 멘토 리뷰 요청

#5 [장인석] Assignment 2: Express API - 유저 회원가입 하기
  Inseok_45/.gitignore
  Inseok_45/app.js
  Inseok_45/db/migrations/20230418053452_create_users_table.sql
Labels: 완료

#7 [탁호진] Assignment 1: Express API - 초기 환경 세팅
  takhojin/.env.sample
  takhojin/.gitignore
  takhojin/app.js
  takhojin/package-lock.json
  takhojin/package.json
Labels: 멘토 리뷰 요청

#10 [하지현] Assignment 3,4,5: Express API - CRUD (1)
  jihyeon/app.js
  jihyeon/db/migrations/20230419052214_posts.sql
Labels: 멘토 리뷰 요청

#11 [탁호진] Assignment 2: Express API - 유저 회원가입 하기
  takhojin/.env.sample
  takhojin/.gitignore
  takhojin/app.js
  takhojin/db/migrations/20230419080018_create_users_table.sql
  takhojin/db/migrations/20230420014948_modify_users_table.sql
  takhojin/package-lock.json
  takhojin/package.json
Labels: 수정 요청

#12 [이지은] Assignment 6,7,8: Express API - CRUD (2)
  Jieun/app.js
  Jieun/db/migrations/20230420010423_create_likes_table.sql
Labels: 완료

#9 [장인석] Assignment 3,4,5: Express API - CRUD(추가 구현)
  Inseok_45/app.js
  Inseok_45/db/migrations/20230418053452_create_users_table.sql
  Inseok_45/db/migrations/20230419054824_create_posts_table.sql
  Inseok_45/db/migrations/20230420063044_create_likes_table.sql
Labels: 멘토 리뷰 요청

#13 [장인석] Assignment 6,7,8: Express API CRUD (2)
  Inseok_45/app.js
  Inseok_45/db/migrations/20230420063044_create_likes_table.sql
Labels: 멘토 리뷰 요청

#16 [탁호진] Assigment 6,7,8 : CRUD 2
  takhojin/app.js
  takhojin/db/migrations/20230421090544_like_users_tables.sql
  takhojin/db/migrations/20230421111840_modify_likes.sql
  takhojin/db/migrations/20230422141618_like_table_uniqueindex_make.sql
Labels: 멘토 리뷰 요청

#17 [이지은] Assignment 9: Project Layered Pattern 적용
  Jieun/app.js
  Jieun/controllers/likeController.js
  Jieun/controllers/postController.js
  Jieun/controllers/userController.js
  Jieun/models/dataSource.js
  Jieun/models/likeDao.js
  Jieun/models/postDao.js
  Jieun/models/userDao.js
  Jieun/package-lock.json
  Jieun/package.json
  Jieun/routes/index.js
  Jieun/routes/likeRouter.js
  Jieun/routes/postRouter.js
  Jieun/routes/userRouter.js
  Jieun/services/likeService.js
  Jieun/services/postService.js
  Jieun/services/userService.js
Labels: 멘토 리뷰 요청

#18 [장인석] Assignment 9: Layered Pattern 적용
  Inseok_45/README.md
  Inseok_45/app.js
  Inseok_45/controllers/likeController.js
  Inseok_45/controllers/postController.js
  Inseok_45/controllers/userController.js
  Inseok_45/models/dataSource.js
  Inseok_45/models/likeDao.js
  Inseok_45/models/postDao.js
  Inseok_45/models/userDao.js
  Inseok_45/routes/index.js
  Inseok_45/routes/likeRouter.js
  Inseok_45/routes/postRouter.js
  Inseok_45/routes/userRouter.js
  Inseok_45/services/likeService.js
  Inseok_45/services/postService.js
  Inseok_45/services/userService.js
  Inseok_45/utils/validation-check.js
Labels: 멘토 리뷰 요청

#19 [하지현] Assignment 9: Layered Pattern 적용
  jihyeon/app.js
  jihyeon/controllers/likesController.js
  jihyeon/controllers/postController.js
  jihyeon/controllers/userController.js
  jihyeon/models/dataSource.js
  jihyeon/models/likesDao.js
  jihyeon/models/postDao.js
  jihyeon/models/userDao.js
  jihyeon/routes/index.js
  jihyeon/routes/likesRoute.js
  jihyeon/routes/postRoute.js
  jihyeon/routes/userRoute.js
  jihyeon/services/likesService.js
  jihyeon/services/postService.js
  jihyeon/services/userService.js
  jihyeon/utils/validation-check.js
Labels: 멘토 리뷰 요청

#20 [탁호진] Assignment 9: Layered Pattern 적용
  takhojin/app.js
  takhojin/controllers/postController.js
  takhojin/controllers/userController.js
  takhojin/models/dataSource.js
  takhojin/models/postDao.js
  takhojin/models/userDao.js
  takhojin/package-lock.json
  takhojin/package.json
  takhojin/routes/index.js
  takhojin/routes/postRouter.js
  takhojin/routes/userRouter.js
  takhojin/services/postService.js
  takhojin/services/userService.js
  takhojin/utils/validation-check.js
Labels: 멘토 리뷰 요청

#22 [탁호진] Assignment bcrypy1
  takhojin/.env.sample
  takhojin/controllers/userController.js
  takhojin/models/userDao.js
  takhojin/package-lock.json
  takhojin/package.json
  takhojin/services/userService.js
Labels: 멘토 리뷰 요청

#23 [하지현] Assignment 1 : Authentication & Authorization
  jihyeon/package-lock.json
  jihyeon/package.json
  jihyeon/services/userService.js
Labels: 멘토 리뷰 요청

#24 [이지은] Assignment 1: Bcrypt를 이용하여 비밀번호 암호화하기
  Jieun/controllers/postController.js
  Jieun/controllers/userController.js
  Jieun/middlewares/bcrypt.js
  Jieun/models/userDao.js
  Jieun/package-lock.json
  Jieun/package.json
  Jieun/services/userService.js
Labels: 멘토 리뷰 요청

#25 [이지은] Assignment2: Bcrypt Verification 및 JWT 발급하기
  Jieun/controllers/userController.js
  Jieun/middlewares/bcrypt.js
  Jieun/models/userDao.js
  Jieun/routes/userRouter.js
  Jieun/services/userService.js
  Jieun/utils/validation-check.js
Labels: 멘토 리뷰 요청

#27 [하지현] Assignment2: Bcrypt Verification 및 JWT 발급하기
  jihyeon/controllers/userController.js
  jihyeon/models/userDao.js
  jihyeon/package-lock.json
  jihyeon/package.json
  jihyeon/routes/userRoute.js
  jihyeon/services/userService.js
  jihyeon/utils/validation-check.js
Labels: 멘토 리뷰 요청

#30 [이지은] Assignment3: 로그인 한 사용자만 게시글 등록하기
  Jieun/middlewares/auth.js
  Jieun/routes/postRouter.js
Labels: 완료

#21 [장인석] Assignment 1,2[수정], 3[추가]: Authentication & Authorization
  Inseok_45/.env.sample
  Inseok_45/.gitignore
  Inseok_45/controllers/postController.js
  Inseok_45/controllers/userController.js
  Inseok_45/middlewares/validate-jwt.js
  Inseok_45/models/postDao.js
  Inseok_45/models/userDao.js
  Inseok_45/package-lock.json
  Inseok_45/package.json
  Inseok_45/routes/postRouter.js
  Inseok_45/routes/userRouter.js
  Inseok_45/services/postService.js
  Inseok_45/services/userService.js
Labels: 멘토 리뷰 요청

#28 [탁호진] Assignmnet 2
  takhojin/.env.sample
  takhojin/controllers/userController.js
  takhojin/models/userDao.js
  takhojin/routes/userRouter.js
  takhojin/services/userService.js
Labels: 멘토 리뷰 요청
